package cobra.controleacesso.web.modelo;

// Generated 24/12/2012 11:14:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tbpessoa generated by hbm2java
 */
@Entity
@Table(name = "tbpessoa")
@SequenceGenerator(name = "id_pessoa_seq", sequenceName = "id_pessoa_seq")
public class Pessoa implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_pessoa_seq")
	private int idPessoa;
	
	private String nmPessoa;
	private Set<Usuario> tbusuarios = new HashSet(0);

	public Pessoa() {
	}

	public Pessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Pessoa(int idPessoa, String nmPessoa, Set <Usuario>tbusuarios) {
		this.idPessoa = idPessoa;
		this.nmPessoa = nmPessoa;
		this.tbusuarios = tbusuarios;
	}

	@Id
	@Column(name = "id_pessoa", unique = true, nullable = false)
	@GeneratedValue
	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	@Column(name = "nm_pessoa")
	public String getNmPessoa() {
		return this.nmPessoa;
	}

	public void setNmPessoa(String nmPessoa) {
		this.nmPessoa = nmPessoa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbpessoa")
	public Set <Usuario>getTbusuarios() {
		return this.tbusuarios;
	}

	public void setTbusuarios(Set <Usuario>tbusuarios) {
		this.tbusuarios = tbusuarios;
	}

}
