package cobra.controleacesso.web.modelo;

// Generated 18/12/2012 20:46:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Tbrecurso generated by hbm2java
 */
@Entity
@Table(name = "tbrecurso")
@SequenceGenerator(name = "id_recurso_seq", sequenceName = "id_recurso_seq")
public class Recurso implements java.io.Serializable {

	private int idRecurso;

	private String nmRecurso;
	private Date dtInclusao;
	private Integer idTiporecurso;
	//private Integer idRecursopai;
	
	private Recurso tbrecursoFilho;
	private String dsRecurso;
	private String lkLink;
	private Boolean fgAtivo;
	private Set <Perfil>tbperfils = new HashSet(0);
	
	public Recurso() {
	}

	public Recurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public Recurso(int idRecurso, String nmRecurso, Date dtInclusao,
			Integer idTiporecurso, Integer idRecursopai, String dsRecurso,
			String lkLink, Boolean fgAtivo, Set <Perfil>tbperfils, Recurso tbreucursoFilho) {
		this.idRecurso = idRecurso;
		this.nmRecurso = nmRecurso;
		this.dtInclusao = dtInclusao;
		this.idTiporecurso = idTiporecurso;
		//this.idRecursopai = idRecursopai;
		this.tbrecursoFilho = tbreucursoFilho;
		this.dsRecurso = dsRecurso;
		this.lkLink = lkLink;
		this.fgAtivo = fgAtivo;
		this.tbperfils = tbperfils;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_recurso_seq")
	@Column(name = "id_recurso", unique = true, nullable = false)
	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	@Column(name = "nm_recurso", nullable = false,  length = 50)
	public String getNmRecurso() {
		return this.nmRecurso;
	}

	public void setNmRecurso(String nmRecurso) {
		this.nmRecurso = nmRecurso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_inclusao", nullable = false, length = 13)
	public Date getDtInclusao() {
		return this.dtInclusao;
	}

	public void setDtInclusao(Date dtInclusao) {
		this.dtInclusao = dtInclusao;
	}

	@Column(name = "id_tiporecurso", nullable = false)
	public Integer getIdTiporecurso() {
		return this.idTiporecurso;
	}

	public void setIdTiporecurso(Integer idTiporecurso) {
		this.idTiporecurso = idTiporecurso;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@Column(name = "id_recursopai", nullable = false)
//	public Integer getIdRecursopai() {
//		return this.idRecursopai;
//	}
//
//	public void setIdRecursopai(Integer idRecursopai) {
//		this.idRecursopai = idRecursopai;
//	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_recursopai", insertable = true, updatable = true, nullable = true)
	public Recurso getTbrecursoFilho() {
		return this.tbrecursoFilho;
	}

	public void setTbrecursoFilho(Recurso tbrecurso) {
		this.tbrecursoFilho = tbrecurso;
	}
	
	@Column(name = "ds_recurso", length = 8000)
	public String getDsRecurso() {
		return this.dsRecurso;
	}

	public void setDsRecurso(String dsRecurso) {
		this.dsRecurso = dsRecurso;
	}

	@Column(name = "lk_link", nullable = false, length = 200)
	public String getLkLink() {
		return this.lkLink;
	}

	public void setLkLink(String lkLink) {
		this.lkLink = lkLink;
	}

	@Column(name = "fg_ativo", nullable = false, columnDefinition = "boolean default true")
	public Boolean getFgAtivo() {
		return this.fgAtivo;
	}

	public void setFgAtivo(Boolean fgAtivo) {
		this.fgAtivo = fgAtivo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tb_recurso_perfil", joinColumns = { @JoinColumn(name = "id_recurso", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_perfil", nullable = false, updatable = false) })
	public Set <Perfil>getTbperfils() {
		return this.tbperfils;
	}

	public void setTbperfils(Set <Perfil>tbperfils) {
		this.tbperfils = tbperfils;
	}

}
