package cobra.controleacesso.web.modelo;

// Generated 24/12/2012 11:25:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tbusuario generated by hbm2java
 */
@Entity
@Table(name = "tbusuario")
@SequenceGenerator(name = "id_usuario_seq", sequenceName = "id_usuario_seq")
public class Usuario implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_usuario_seq")
	private int idUsuario;
	
//	@JoinColumn(name = "id_pessoa", referencedColumnName = "id_pessoa")  
//	@ManyToOne
	private Pessoa tbpessoa;
	
	private String nmLogin;
	private String dsSenha;
	private boolean fgAtivo;
	private Set<Perfil> tbperfils = new HashSet(0);
	
	//private Integer idPessoa;
	
	public Usuario(int idUsuario, String nmLogin, String dsSenha,
			boolean fgAtivo) {
		this.idUsuario = idUsuario;
		this.nmLogin = nmLogin;
		this.dsSenha = dsSenha;
		this.fgAtivo = fgAtivo;
	}

	public Usuario(int idUsuario, Pessoa tbpessoa, String nmLogin,
			String dsSenha, boolean fgAtivo, Set <Perfil> tbperfils, Integer idPessoa) {
		this.idUsuario = idUsuario;
		this.tbpessoa = tbpessoa;
		this.nmLogin = nmLogin;
		this.dsSenha = dsSenha;
		this.fgAtivo = fgAtivo;
		this.tbperfils = tbperfils;
		//this.idPessoa = idPessoa;
	}

	@Id
	@Column(name = "id_usuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pessoa")
	public Pessoa getTbpessoa() {
		return this.tbpessoa;
	}

	public void setTbpessoa(Pessoa tbpessoa) {
		this.tbpessoa = tbpessoa;
	}

	@Column(name = "nm_login", nullable = false, length = 50)
	public String getNmLogin() {
		return this.nmLogin;
	}

	public void setNmLogin(String nmLogin) {
		this.nmLogin = nmLogin;
	}

	@Column(name = "ds_senha", nullable = false)
	public String getDsSenha() {
		return this.dsSenha;
	}

	public void setDsSenha(String dsSenha) {
		this.dsSenha = dsSenha;
	}

	@Column(name = "fg_ativo", nullable = false)
	public boolean isFgAtivo() {
		return this.fgAtivo;
	}

	public void setFgAtivo(boolean fgAtivo) {
		this.fgAtivo = fgAtivo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbusuario_perfil", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_perfil", nullable = false, updatable = false) })
	public Set<Perfil> getTbperfils() {
		return this.tbperfils;
	}

	public void setTbperfils(Set <Perfil>tbperfils) {
		this.tbperfils = tbperfils;
	}
	
	public Usuario() {
	}
	
	/**
	 * @return
	 */
//	@Column(name = "id_pessoa")
//	public Integer getIdPessoa() {
//		return this.idPessoa;
//	}
//
//	public void setIdPessoa(Integer idPessoa) {
//		this.idPessoa = idPessoa;
//	}

}
