package controleacesso.web.modelo;

// Generated 18/12/2012 20:46:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tbperfil generated by hbm2java
 */
@Entity
@Table(name = "tbperfil")
@SequenceGenerator(name = "id_perfil_seq", sequenceName = "id_perfil_seq")
public class Perfil implements java.io.Serializable {

	
	private int idPerfil;
	
	private String dsPerfil;
	private Boolean fgAtivo;
	private Set <Recurso> tbrecursos = new HashSet(0);
	private Set <Usuario>tbusuarios = new HashSet(0);

	public Perfil() {
	}

	public Perfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public Perfil(int idPerfil, String dsPerfil, Boolean fgAtivo,
			Set <Recurso> tbrecursos, Set <Usuario>tbusuarios) {
		this.idPerfil = idPerfil;
		this.dsPerfil = dsPerfil;
		this.fgAtivo = fgAtivo;
		this.tbrecursos = tbrecursos;
		this.tbusuarios = tbusuarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_perfil_seq")
	@Column(name = "id_perfil", unique = true, nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "ds_perfil", length = 50)
	public String getDsPerfil() {
		return this.dsPerfil;
	}

	public void setDsPerfil(String dsPerfil) {
		this.dsPerfil = dsPerfil;
	}

	@Column(name = "fg_ativo")
	public Boolean getFgAtivo() {
		return this.fgAtivo;
	}

	public void setFgAtivo(Boolean fgAtivo) {
		this.fgAtivo = fgAtivo;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tbperfils")
	public Set<Recurso> getTbrecursos() {
		return this.tbrecursos;
	}

	public void setTbrecursos(Set <Recurso>tbrecursos) {
		this.tbrecursos = tbrecursos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tbperfils")
	public Set <Usuario> getTbusuarios() {
		return this.tbusuarios;
	}

	public void setTbusuarios(Set <Usuario>tbusuarios) {
		this.tbusuarios = tbusuarios;
	}

}
